version: '2'
services:
  emulator:
    environment:
        - DISPLAY
    privileged: true
    network_mode: "host"
    image: "pinfake/android-emulator-x11:${EMULATOR_DISTRO}"
    volumes:
        - "/usr/lib:/usr/lib"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
  development:
    depends_on:
        - "emulator"
    privileged: true
    network_mode: "host"
    image: "pinfake/android-react-native"
    volumes:
        - "${HOME}:/root/u"
